// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHhaOAhUdKj3l508FmmcJ0CdxC8SFP8Xo',
    appId: '1:266459797324:web:b3a9bdefbc363ce7eba1e9',
    messagingSenderId: '266459797324',
    projectId: 'popsign-main',
    authDomain: 'popsign-main.firebaseapp.com',
    storageBucket: 'popsign-main.firebasestorage.app',
    measurementId: 'G-DXQZ68L6WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNm_0znNSOT9Ga_EM1EX7A3Th-RT0f6c8',
    appId: '1:266459797324:android:9e3abdafbe17f27eeba1e9',
    messagingSenderId: '266459797324',
    projectId: 'popsign-main',
    storageBucket: 'popsign-main.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvPqkJJAR_F0auS1zdbj3j_7Pklhgyhsg',
    appId: '1:266459797324:ios:0d982da93a9d0bdfeba1e9',
    messagingSenderId: '266459797324',
    projectId: 'popsign-main',
    storageBucket: 'popsign-main.firebasestorage.app',
    iosBundleId: 'com.example.popsign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvPqkJJAR_F0auS1zdbj3j_7Pklhgyhsg',
    appId: '1:266459797324:ios:0d982da93a9d0bdfeba1e9',
    messagingSenderId: '266459797324',
    projectId: 'popsign-main',
    storageBucket: 'popsign-main.firebasestorage.app',
    iosBundleId: 'com.example.popsign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHhaOAhUdKj3l508FmmcJ0CdxC8SFP8Xo',
    appId: '1:266459797324:web:ef26fef4ea452d7aeba1e9',
    messagingSenderId: '266459797324',
    projectId: 'popsign-main',
    authDomain: 'popsign-main.firebaseapp.com',
    storageBucket: 'popsign-main.firebasestorage.app',
    measurementId: 'G-L1DHJK5G1K',
  );
}
